Region = "us-east-1"
[Tags]
  
  [tags.alpha]
  Key = "Creator"
  Value = "Ramon"

  [tags.beta]
  Key = "purpose"
  Value = "test"
  
  [tags.delta]
  Key = "cost:group"
  Value = "backlot"
  
  [tags.gamma]
  Key = "dummie"
  Value = "yoshio"
