Region = "us-east-1"
[Tags]
  
  [tags.alpha]
  Key = "Creator"
  Value = "ramon"

  [tags.beta]
  Key = "Creator"
  Value = "german"
  
  [tags.delta]
  Key = "cost:group"
  Value = "backlot"
  
  [tags.gamma]
  Key = "Creator"
  Value = "yoshio"
