[Tags]

  [tags.alpha]
  Key = "Creator"
  Value = "Ramon"

  [tags.beta]
  Key = "Purpose"
  Value = "test"


[Servers]

  [servers.alpha]
  ip = "10.0.0.1"
  dc = "eqdc10"

  [servers.beta]
  ip = "10.0.0.2"
  dc = "eqdc10"

